services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devops-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - devops-network

volumes:
  mysql-data:

networks:
  devops-network:
    driver: bridge
